version: '3'

services:
  bitwarden:
    image: vaultwarden/server:latest
    restart: always
    networks:
      - default
      - reverseproxy_traefik
    volumes:
      - bitwarden:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverseproxy_traefik
      - traefik.http.routers.bitwarden-ui.rule=Host(`pwd.alex-j-butler.com`)
      - traefik.http.routers.bitwarden-ui.service=bitwarden-ui
      - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
      - traefik.http.routers.bitwarden-websocket.rule=Host(`pwd.alex-j-butler.com`) && Path(`/notifications/hub`)
      - traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012
      - "traefik.http.routers.bitwarden-ui.tls.certresolver=myresolver"
      - "traefik.http.routers.bitwarden-websocket.tls.certresolver=myresolver"

volumes:
  bitwarden:
    driver: local

networks:
  reverseproxy_traefik:
    external: true
