version: "3"

services:
  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Australia/Brisbane
    volumes:
      - ./config:/config
