version: "3"

services:
  meilisearch:
    image: getmeili/meilisearch
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY:?MEILISEARCH_KEY}
      - MEILI_ENV=production
    ports:
      - 7700:7700
    volumes:
      - ./meilisearch:/meili_data

  bar-assistant:
    image: kmikus12/bar-assistant-server
    depends_on:
      - meilisearch
    environment:
      - APP_URL=http://10.0.3.3:8003
      - MEILISEARCH_KEY=${MEILISEARCH_KEY:?MEILISEARCH_KEY}
      - MEILISEARCH_HOST=http://meilisearch:7700
    volumes:
      - ba-storage:/var/www/cocktails/storage
    ports:
      - 8003:80

  salt-rim:
    image: kmikus12/salt-rim
    depends_on:
      - meilisearch
      - bar-assistant
    environment:
      - API_URL=http://10.0.3.3:8003
      - MEILISEARCH_HOST=http://10.0.3.3:7700
    ports:
      - 8083:8080

volumes:
  ba-storage: