version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.7
    # Enables the web UI and tells Traefik to listen to docker
    command: >-
      --api.insecure=true --providers.docker --providers.docker.network=reverseproxy_traefik --providers.docker.endpoint=unix:///var/run/docker.sock --entryPoints.web.address=:80 --entryPoints.websecure.address=:443
      --entryPoints.syslog.address=:1514 --entryPoints.syslogudp.address=:1514/udp
      --entryPoints.gelf.address=:12201 --entryPoints.gelfudp.address=:12201/udp
      --certificatesresolvers.myresolver.acme.tlschallenge=true
      --certificatesresolvers.myresolver.acme.email=alex@alex-j-butler.com
      --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      --providers.file.directory=/FileProvider/
      --providers.file.watch=true
      --log.level=WARN
      --accesslog
      --accesslog.filepath=/dev/stderr
    #labels:
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./FileProvider:/FileProvider"
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverseproxy_traefik

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    env_file:
      - traefik.env
    networks:
      - reverseproxy_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"

networks:
  reverseproxy_traefik:
    external: true
