version: '3.6'

services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:2.1.0-latest
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    volumes:
      - ./monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      reverseproxy_traefik:
    ports:
      - "8082:5000"
      - "8083:8000"
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverseproxy_traefik
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true

      - traefik.http.routers.checkmk-https.rule=Host(`checkmk.alex-j-butler.com`)
      - traefik.http.routers.checkmk-https.entrypoints=websecure
      - traefik.http.routers.checkmk-https.tls=true
      - traefik.http.routers.checkmk-https.service=checkmk

      - traefik.http.routers.checkmk-http.rule=Host(`checkmk.alex-j-butler.com`)
      - traefik.http.routers.checkmk-http.entrypoints=web
      - traefik.http.routers.checkmk-http.middlewares=redirect-https
      - traefik.http.routers.checkmk-http.service=checkmk

      - traefik.http.services.checkmk.loadbalancer.server.port=5000

      - "traefik.http.routers.checkmk-https.tls.certresolver=myresolver"

networks:
  reverseproxy_traefik:
    external: true
