version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=powerdnsadmin
      - MYSQL_USER=pdns 
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?SQL_PASS}
    restart: always
    volumes:
      - pda-mysql:/var/lib/mysql
  pdns:
    image: pschiffe/pdns-mysql
    restart: always
    depends_on:
      - db
    links:
      - "db:mysql"
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    environment:
      - PDNS_gmysql_host=db
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=pdns
      - PDNS_gmysql_dbname=powerdnsadmin
      - PDNS_gmysql_password=${MYSQL_PASSWORD}
      - PDNS_master=yes 
      - PDNS_api=yes
      - PDNS_api_key=${PDNS_API_KEY} 
      - PDNSCONF_API_KEY=${PDNSCONF_API_KEY} 
      - PDNS_webserver=yes 
      - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24 
      - PDNS_webserver_address=0.0.0.0 
      - PDNS_webserver_password=${PDNS_WEBSERVER_PASSWORD} 
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500 
      - PDNS_allow_notify_from=0.0.0.0 
      - PDNS_allow_axfr_ips=127.0.0.1 

  web_app:
    image: ngoduykhanh/powerdns-admin:latest
    container_name: powerdns_admin
    #ports:
    #  - "8080:80"
    networks:
      - default
      - reverseproxy_traefik
    depends_on:
      - db
    restart: always
    links:
      - db:mysql
      - pdns:pdns
    logging:
      driver: json-file
      options:
        max-size: 50m
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverseproxy_traefik
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true

      - traefik.http.routers.pdns-admin-https.rule=Host(`pdns-admin.alex-j-butler.com`)
      - traefik.http.routers.pdns-admin-https.entrypoints=websecure
      - traefik.http.routers.pdns-admin-https.tls=true
      - traefik.http.routers.pdns-admin-https.service=bitwarden-ui

      - traefik.http.routers.pdns-admin-http.rule=Host(`pdns-admin.alex-j-butler.com`)
      - traefik.http.routers.pdns-admin-http.entrypoints=web
      - traefik.http.routers.pdns-admin-http.middlewares=redirect-https
      - traefik.http.routers.pdns-admin-http.service=pdns

      - traefik.http.services.pdns.loadbalancer.server.port=80

      - "traefik.http.routers.pdns-admin-https.tls.certresolver=myresolver"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pdns:${MYSQL_PASSWORD}@db/powerdnsadmin
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG

volumes:
  pda-mysql:
    driver: local

networks:
  reverseproxy_traefik:
    external: true
