[http]
  [http.middlewares]
    [http.middlewares.redirect-https]
      [http.middlewares.redirect-https.redirectScheme]
        scheme = "https"
        permanent = "true"
  # Add the router
  [http.routers]
    [http.routers.fluidd-https]
      entryPoints = ["websecure"]
      service = "service-fluidd"
      rule = "Host(`3d.alex-j-butler.com`)"
      middlewares = ["traefik-forward-auth@docker"]
      [http.routers.fluidd-https.tls]
        certresolver="myresolver"
    [http.routers.fluidd-http]
      entryPoints = ["web"]
      service = "service-fluidd"
      rule = "Host(`3d.alex-j-butler.com`)"
      middlewares = ["redirect-https"]
    [http.routers.ha-https]
      entryPoints = ["websecure"]
      service = "service-ha"
      rule = "Host(`homeassistant.alex-j-butler.com`)"
      [http.routers.ha-https.tls]
        certresolver="myresolver"
    [http.routers.ha-http]
      entryPoints = ["web"]
      service = "service-ha"
      rule = "Host(`homeassistant.alex-j-butler.com`)"
      middlewares = ["redirect-https"]

    [http.routers.plex-https]
      entryPoints = ["websecure"]
      service = "service-plex"
      rule = "Host(`plex.alex-j-butler.com`)"
      [http.routers.plex-https.tls]
        certresolver="myresolver"
    [http.routers.plex-sonarr-https]
      entryPoints = ["websecure"]
      service = "service-plex-sonarr"
      rule = "Host(`plex.alex-j-butler.com`) && Path(`/sonarr`)"
      [http.routers.plex-sonarr-https.tls]
        certresolver="myresolver"
    [http.routers.plex-radarr-https]
      entryPoints = ["websecure"]
      service = "service-plex-radarr"
      rule = "Host(`plex.alex-j-butler.com`) && Path(`/radarr`)"
      [http.routers.plex-radarr-https.tls]
        certresolver="myresolver"
    [http.routers.plex-http]
      entryPoints = ["web"]
      service = "service-plex"
      rule = "Host(`plex.alex-j-butler.com`)"
      middlewares = ["redirect-https"]

  # Add the service
    [http.services.service-fluidd]
      [http.services.service-fluidd.loadBalancer]
        [[http.services.service-fluidd.loadBalancer.servers]]
          url = "http://10.0.1.39"
    [http.services.service-ha]
      [http.services.service-ha.loadBalancer]
        [[http.services.service-ha.loadBalancer.servers]]
          url = "http://10.0.3.5:8123"
          port = "8123"
    [http.services.service-plex]
      [http.services.service-plex.loadBalancer]
        [[http.services.service-plex.loadBalancer.servers]]
          url = "http://10.0.3.23:32400"
    [http.services.service-plex-sonarr]
      [http.services.service-plex-sonarr.loadBalancer]
        [[http.services.service-plex-sonarr.loadBalancer.servers]]
          url = "http://10.0.3.23:8989"
    [http.services.service-plex-radarr]
      [http.services.service-plex-radarr.loadBalancer]
        [[http.services.service-plex-radarr.loadBalancer.servers]]
          url = "http://10.0.3.23:7878"
