[http]
  [http.middlewares]
    [http.middlewares.redirect-https]
      [http.middlewares.redirect-https.redirectScheme]
        scheme = "https"
        permanent = "true"
  # Add the router
  [http.routers]
    [http.routers.fluidd-https]
      entryPoints = ["websecure"]
      service = "service-fluidd"
      rule = "Host(`3d.alex-j-butler.com`)"
      middlewares = ["traefik-forward-auth@docker"]
      [http.routers.fluidd-https.tls]
        certresolver="myresolver"
    [http.routers.fluidd-http]
      entryPoints = ["web"]
      service = "service-fluidd"
      rule = "Host(`3d.alex-j-butler.com`)"
      middlewares = ["redirect-https"]
    [http.routers.ha-https]
      entryPoints = ["websecure"]
      service = "service-ha"
      rule = "Host(`homeassistant.alex-j-butler.com`)"
      [http.routers.ha-https.tls]
        certresolver="myresolver"
    [http.routers.ha-http]
      entryPoints = ["web"]
      service = "service-ha"
      rule = "Host(`homeassistant.alex-j-butler.com`)"
      middlewares = ["redirect-https"]

  # Add the service
    [http.services.service-fluidd]
      [http.services.service-fluidd.loadBalancer]
        [[http.services.service-fluidd.loadBalancer.servers]]
          url = "http://10.0.1.39"
    [http.services.service-ha]
      [http.services.service-ha.loadBalancer]
        [[http.services.service-ha.loadBalancer.servers]]
          url = "http://10.0.3.5"
          port = "8123"
